Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4048
    vb.cpus = 2
   end
  config.vm.provision "shell", path: "scripts/base.sh"
end
